import { IFileTypes } from "@/types/file"

const FileTypes: IFileTypes = {
	audio: ["mp3", "wav", "ogg", "m4a", "webm", "3gp"],
	video: [
		"mp4",
		"webm",
		"ogg",
		"mov",
		"avi",
		"wmv",
		"flv",
		"mkv",
		"m4v",
		"mpg",
		"mpeg",
		"3gp",
		"3g2",
	],
	document: ["ppt", "pptx", "doc", "docx", "pdf", "xls", "xlsx"],
	code: [
		{ name: "bat", ext: ["bat"] },
		{ name: "c", ext: ["c"] },
		{ name: "cpp", ext: ["cpp"] },
		{ name: "csharp", ext: ["cs"] },
		{ name: "css", ext: ["css"] },
		{ name: "dockerfile", ext: ["dockerfile"] },
		{ name: "go", ext: ["go"] },
		{ name: "graphql", ext: ["graphql"] },
		{ name: "html", ext: ["html"] },
		{ name: "java", ext: ["java"] },
		{ name: "javascript", ext: ["js", "jsx", "vue", "ang"] },
		{ name: "json", ext: ["json"] },
		{ name: "kotlin", ext: ["kt"] },
		{ name: "less", ext: ["less"] },
		{ name: "lua", ext: ["lua"] },
		{ name: "markdown", ext: ["md", "mdx"] },
		{ name: "mysql", ext: ["sql"] },
		{ name: "pascal", ext: ["pas"] },
		{ name: "perl", ext: ["pl"] },
		{ name: "pgsql", ext: ["pgsql"] },
		{ name: "php", ext: ["php"] },
		{ name: "powershell", ext: ["ps1"] },
		{ name: "pug", ext: ["pug"] },
		{ name: "python", ext: ["py"] },
		{ name: "r", ext: ["r"] },
		{ name: "redis", ext: ["conf"] },
		{ name: "ruby", ext: ["rb"] },
		{ name: "rust", ext: ["rs"] },
		{ name: "scss", ext: ["scss"] },
		{ name: "shell", ext: ["sh"] },
		{ name: "sol", ext: ["sol"] },
		{ name: "sql", ext: ["sql"] },
		{ name: "swift", ext: ["swift"] },
		{ name: "typescript", ext: ["ts", "tsx"] },
		{ name: "xml", ext: ["xml"] },
		{ name: "yaml", ext: ["yaml"] },
		{ name: "csv", ext: ["csv"] },
	],
}

export default FileTypes
