import { IPreference } from "@/types/preferences"

export const Preferences: IPreference[] = [
	{
		title: "Creativity",
		key: "creativity",
		options: [
			{ value: "art", icon: "🎨", label: "Art" },
			{ value: "dancing", icon: "💃", label: "Dancing" },
			{ value: "craft", icon: "✏️", label: "Craft" },
			{ value: "design", icon: "💓", label: "Design" },
			{ value: "makeUp", icon: "💄", label: "Make-up" },
			{ value: "makingVideos", icon: "🎥", label: "Making Videos" },
			{ value: "photography", icon: "📸", label: "Photography" },
			{ value: "singing", icon: "🎤", label: "Singing" },
			{ value: "writing", icon: "📝", label: "Writing" },
		],
	},
	{
		title: "Going Out",
		key: "goingOut",
		options: [
			{
				value: "museumGalleries",
				icon: "🖼️",
				label: "Museum & Galleries",
			},
			{ value: "bars", icon: "🍹", label: "Bars" },
			{ value: "design", icon: "💓", label: "Design" },
			{ value: "dragShoes", icon: "👠", label: "Drag Shoes" },
			{ value: "festivals", icon: "🎉", label: "Festivals" },
			{ value: "gigs", icon: "🎤", label: "Gigs" },
			{ value: "karaoke", icon: "🎤", label: "Karaoke" },
			{ value: "lgbtNightlife", icon: "🏳️‍🌈", label: "LGBT+ Nightlife" },
			{ value: "nightclubs", icon: "🕺", label: "Nightclubs" },
			{ value: "standup", icon: "🎙️", label: "Standup" },
			{ value: "theater", icon: "🎭", label: "Theater" },
		],
	},
	{
		title: "Staying In",
		key: "stayingIn",
		options: [
			{ value: "baking", icon: "🍰", label: "Baking" },
			{ value: "boardGames", icon: "🎲", label: "Board Games" },
			{ value: "cooking", icon: "🍳", label: "Cooking" },
			{ value: "gardening", icon: "🌱", label: "Gardening" },
			{ value: "videoGames", icon: "🎮", label: "Video Games" },
		],
	},
	{
		title: "Film & TV",
		key: "filmTv",
		options: [
			{ value: "documentaries", icon: "📽️", label: "Documentaries" },
			{
				value: "actionAdventure",
				icon: "💥",
				label: "Action & Adventure",
			},
			{ value: "animated", icon: "🎬", label: "Animated" },
			{ value: "anime", icon: "🍱", label: "Anime" },
			{ value: "bollywood", icon: "🎥", label: "Bollywood" },
			{ value: "comedy", icon: "😂", label: "Comedy" },
			{ value: "cookingShows", icon: "🍳", label: "Cooking Shows" },
			{ value: "crime", icon: "🕵️‍♂️", label: "Crime" },
			{ value: "drama", icon: "🎭", label: "Drama" },
			{ value: "fantasy", icon: "🧙‍♂️", label: "Fantasy" },
			{ value: "gameShows", icon: "📺", label: "Game Shows" },
			{ value: "horror", icon: "👻", label: "Horror" },
			{ value: "indie", icon: "🎬", label: "Indie" },
			{ value: "kdrama", icon: "🇰🇷", label: "K-drama" },
			{ value: "romCom", icon: "💑", label: "Rom-com" },
			{ value: "romance", icon: "💑", label: "Romance" },
			{ value: "sciFi", icon: "👽", label: "Sci-fi" },
			{ value: "superhero", icon: "🦸‍♂️", label: "Superhero" },
		],
	},
	{
		title: "Reading",
		key: "reading",
		options: [
			{ value: "biographies", icon: "📚", label: "Biographies" },
			{
				value: "actionAdventure",
				icon: "💥",
				label: "Action & Adventure",
			},
			{ value: "comedy", icon: "😂", label: "Comedy" },
			{ value: "crime", icon: "🕵️‍♂️", label: "Crime" },
			{ value: "fantasy", icon: "🧙‍♂️", label: "Fantasy" },
			{ value: "history", icon: "📚", label: "History" },
			{ value: "horror", icon: "👻", label: "Horror" },
			{ value: "philosophy", icon: "🤔", label: "Philosophy" },
			{ value: "sciFi", icon: "👽", label: "Sci-fi" },
			{ value: "romance", icon: "💑", label: "Romance" },
			{ value: "science", icon: "🔬", label: "Science" },
			{ value: "thriller", icon: "🔪", label: "Thriller" },
		],
	},
	{
		title: "Music",
		key: "music",
		options: [
			{ value: "afro", icon: "🎵", label: "Afro" },
			{ value: "arab", icon: "🎵", label: "Arab" },
			{ value: "blues", icon: "🎵", label: "Blues" },
			{ value: "classical", icon: "🎵", label: "Classical" },
			{ value: "country", icon: "🎵", label: "Country" },
			{ value: "desi", icon: "🎵", label: "Desi" },
			{ value: "edm", icon: "🎵", label: "EDM" },
			{ value: "electronic", icon: "🎵", label: "Electronic" },
			{ value: "folkAcoustic", icon: "🎵", label: "Folk & Acoustic" },
			{ value: "funk", icon: "🎵", label: "Funk" },
			{ value: "hipHop", icon: "🎵", label: "Hip Hop" },
			{ value: "house", icon: "🎵", label: "House" },
			{ value: "indie", icon: "🎵", label: "Indie" },
			{ value: "jazz", icon: "🎵", label: "Jazz" },
			{ value: "kpop", icon: "🎵", label: "K-pop" },
			{ value: "latin", icon: "🎵", label: "Latin" },
			{ value: "metal", icon: "🎵", label: "Metal" },
			{ value: "pop", icon: "🎵", label: "Pop" },
			{ value: "punjabi", icon: "🎵", label: "Punjabi" },
			{ value: "punk", icon: "🎵", label: "Punk" },
			{ value: "rB", icon: "🎵", label: "R&B" },
			{ value: "rap", icon: "🎵", label: "Rap" },
			{ value: "reggae", icon: "🎵", label: "Reggae" },
			{ value: "rock", icon: "🎵", label: "Rock" },
			{ value: "soul", icon: "🎵", label: "Soul" },
			{ value: "sufi", icon: "🎵", label: "Sufi" },
			{ value: "techno", icon: "🎵", label: "Techno" },
		],
	},
	{
		title: "Food & Drink",
		key: "foodDrinking",
		options: [
			{ value: "beer", icon: "🍺", label: "Beer" },
			{ value: "biryani", icon: "🍛", label: "Biryani" },
			{ value: "bobaTea", icon: "🧋", label: "Boba Tea" },
			{ value: "cocktails", icon: "🍹", label: "Cocktails" },
			{ value: "coffee", icon: "☕", label: "Coffee" },
			{ value: "foodie", icon: "🍽️", label: "Foodie" },
			{ value: "maggi", icon: "🍝", label: "Maggi" },
			{ value: "pizza", icon: "🍕", label: "Pizza" },
			{ value: "sushi", icon: "🍣", label: "Sushi" },
			{ value: "sweetTooth", icon: "🍰", label: "Sweet Tooth" },
			{ value: "takeout", icon: "🥡", label: "Takeout" },
			{ value: "tea", icon: "🍵", label: "Tea" },
			{ value: "vegan", icon: "🌱", label: "Vegan" },
			{ value: "vegetarian", icon: "🥗", label: "Vegetarian" },
			{ value: "whisky", icon: "🥃", label: "Whisky" },
			{ value: "wine", icon: "🍷", label: "Wine" },
		],
	},
	{
		title: "Traveling",
		key: "traveling",
		options: [
			{ value: "backpacking", icon: "🎒", label: "Backpacking" },
			{ value: "beaches", icon: "🏖️", label: "Beaches" },
			{ value: "camping", icon: "⛺", label: "Camping" },
			{ value: "cityBreaks", icon: "🏙️", label: "City Breaks" },
			{ value: "countryEscapes", icon: "🌳", label: "Country Escapes" },
			{ value: "fishingTrips", icon: "🎣", label: "Fishing Trips" },
			{ value: "hikingTrips", icon: "🥾", label: "Hiking Trips" },
			{ value: "roadTrips", icon: "🚗", label: "Road Trips" },
			{ value: "spaWeekends", icon: "💆‍♀️", label: "Spa Weekends" },
			{ value: "winterSports", icon: "⛷️", label: "Winter Sports" },
		],
	},
	{
		title: "Pets",
		key: "pets",
		options: [
			{ value: "birds", icon: "🐦", label: "Birds" },
			{ value: "cats", icon: "🐱", label: "Cats" },
			{ value: "dogs", icon: "🐶", label: "Dogs" },
			{ value: "fish", icon: "🐟", label: "Fish" },
			{ value: "turtles", icon: "🐢", label: "Turtles" },
		],
	},
	{
		title: "Values & Traits",
		key: "valuesTraits",
		options: [
			{ value: "ambition", icon: "🚀", label: "Ambition" },
			{ value: "beingActive", icon: "🏃‍♀️", label: "Being Active" },
			{
				value: "beingFamilyOriented",
				icon: "👨‍👩‍👧",
				label: "Being Family-oriented",
			},
			{ value: "creativity", icon: "🎨", label: "Creativity" },
			{
				value: "beingOpenMinded",
				icon: "🌐",
				label: "Being Open-minded",
			},
			{ value: "confidence", icon: "🤩", label: "Confidence" },
			{ value: "empathy", icon: "❤️", label: "Empathy" },
			{ value: "intelligence", icon: "🧠", label: "Intelligence" },
			{ value: "positivity", icon: "😊", label: "Positivity" },
			{ value: "selfAwareness", icon: "🧠", label: "Self-awareness" },
			{
				value: "senseOfAdventure",
				icon: "🌍",
				label: "Sense Of Adventure",
			},
			{ value: "senseOfHumour", icon: "😄", label: "Sense Of Humour" },
			{ value: "socialAwareness", icon: "🌎", label: "Social Awareness" },
		],
	},
]
